name: Print action
run-name: ${{ github.actor }}'s test github action
on: push
jobs:
  print:
    name: my first print job
    runs-on: ubuntu-latest
    steps:
      - name: first print
        run: echo this is a first print
