name: Print action
run-name: ${{ github.actor }}'s test github action
on: push
jobs:
  first_print:
    name: my first print job
    runs-on: ubuntu-latest
    steps:
      - name: first print
        run: echo this is a first print
      - name: impossible action
        run: ./file_doesn_t_exist.sh
  second_print:
    if: always()
    name: my second print job
    # needs: first_print
    runs-on: ubuntu-latest
    steps:
      - name: second print
        run: echo tis is a second print
